### ISSUE TITLE
ItemSpawnEvent

### ISSUE THREAD

**Issue by zeroman9x** [magnusulf/DropNames#1]
Got a problem with ItemSpawnEvent. Can you help me fixxing this ?

```
[05:51:36] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to DropNames v0.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Server.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Server.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Server.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Server.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:305) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1017) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.World.addEntity(World.java:987) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:630) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:620) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:554) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:599) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Server.jar:git-Spigot-db6de12-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_71]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_71]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Server.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
    at dk.muj.dropnames.DropNames.setItemName(DropNames.java:48) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Server.jar:git-Spigot-db6de12-18fbb24]
    ... 21 more

```

**Comment by magnusulf** [comment]
There has been a rework and this is old. Closing. I am sorry for not responding back when this issue was opened.
